### ISSUE TITLE
Can you add t and T highlights?

### ISSUE THREAD

**Issue by askfiy** [kevinhwang91/nvim-fFHighlight#2]
tT and fF are equally convenient, will they be added by the plan?

**Comment by kevinhwang91** [comment]
Sorry, no plan. You can give https://github.com/rhysd/clever-f.vim a try. I think highlighting `tT` in normal and visual mode is useless.

On the codebase side, the logic of `t` + `;` or `t` +`,` is so weird, I must hijack `;` and `,` to remap the built-in behavior to get bug-free.

FYI: https://www.reddit.com/r/neovim/comments/tzz5v7/share_a_ff_highlight_plugin/

**Comment by askfiy** [comment]
okay, thank you
